/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepositoryIndexRouteImport } from './routes/repository/index'
import { Route as RepositoryAddRouteImport } from './routes/repository/add'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryIndexRoute = RepositoryIndexRouteImport.update({
  id: '/repository/',
  path: '/repository/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryAddRoute = RepositoryAddRouteImport.update({
  id: '/repository/add',
  path: '/repository/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/repository/add': typeof RepositoryAddRoute
  '/repository': typeof RepositoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/repository/add': typeof RepositoryAddRoute
  '/repository': typeof RepositoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/repository/add': typeof RepositoryAddRoute
  '/repository/': typeof RepositoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/register' | '/repository/add' | '/repository'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/repository/add' | '/repository'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/repository/add'
    | '/repository/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RepositoryAddRoute: typeof RepositoryAddRoute
  RepositoryIndexRoute: typeof RepositoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository/': {
      id: '/repository/'
      path: '/repository'
      fullPath: '/repository'
      preLoaderRoute: typeof RepositoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository/add': {
      id: '/repository/add'
      path: '/repository/add'
      fullPath: '/repository/add'
      preLoaderRoute: typeof RepositoryAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RepositoryAddRoute: RepositoryAddRoute,
  RepositoryIndexRoute: RepositoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
